language: python

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
   - python: 2.7
     os: linux
   - python: 3.3
     os: linux
   - python: 3.4
     os: linux
   - python: 3.5
     os: linux
   - python: 3.6
     os: linux
   - python: 3.7
     dist: xenial

# command to install dependencies
install:
  - "pip install setuptools wheel"
  - "pip install --trusted-host www.silx.org -r ci/requirements_travis.txt"
  - "python ci/info_platform.py"
  - "python setup.py build bdist_wheel"
  - "pip install ."

# command to run tests
script:
  - "python setup.py build test"
  - "python ./run_tests.py --installed"
