language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
   - python: 3.7
     dist: xenial
     sudo: true

# command to install dependencies
install:
  - "pip install setuptools wheel"
  - "pip install --trusted-host www.silx.org -r ci/requirements_travis.txt"
  - "python ci/info_platform.py"
  - "python setup.py build bdist_wheel"
  - "pip install ."
# command to run tests
script:
  - "python setup.py build test"
  - "python ./run_tests.py --installed"
